apiVersion: apps/v1
kind: Deployment
metadata:
  name: koen-deployment
  labels:
    app: koen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koen
  template:
    metadata:
      labels:
        app: koen
    spec:
      containers:
      - name: koencontainer
        image: koen199/testkubernetes:0.0.1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: koen-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30123
  selector:
    app: koen
